config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :order_items
  resources :orders
  resources :products
  resource  :cart, only: [:show]
  resources :charges
  resources :homepage
  root 'products#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/order.rb
class Order < ApplicationRecord
    has_many :order_items
    before_save :update_total
    before_create :update_status

    def calculate_total
      self.order_items.collect { |item| item.product.price * item.quantity }.sum
    end

    private

    def update_status
      if self.status == nil?
        self.status = "In progress"
      end
    end

    def update_total
      self.total_price = calculate_total
    end
  end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :product
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :order_items, dependent: :destroy
  has_attached_file :image, styles: { large: "600x600", medium: "300x300", thumb: "150x150#"}
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
  belongs_to :user
  # has_many :materials, inverse_of: :product, dependent: :destroy
  # accepts_nested_attributes_for :materials, reject_if: :all_blank, allow_destroy: true
  # has_many :ingredients, inverse_of: :product, dependent: :destroy
  # accepts_nested_attributes_for :ingredients, reject_if: :all_blank, allow_destroy: true
  # has_many :sizes, inverse_of: :product, dependent: :destroy
  # accepts_nested_attributes_for :sizes, reject_if: :all_blank, allow_destroy: true
  # has_many :images, inverse_of: :product, dependent: :destroy
  # accepts_nested_attributes_for :images, reject_if: :all_blank, allow_destroy: true
  # belongs_to :category
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :products
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery
    helper_method :current_order

    def current_order
      if session[:order_id]
        Order.find(session[:order_id])
      else
        Order.new
      end
    end
  end

app/controllers/carts_controller.rb
class CartsController < ApplicationController

    def show
      @order_items = current_order.order_items
    end
  end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController

    Stripe.api_key = ENV['sk_test_1kTxBNShxMhrXMQh6ngWPp8h']
    def new
  end

  def create
    # Amount in cents

    customer = Stripe::Customer.create(
      :email => params[:stripeEmail],
      :source  => params[:stripeToken]
    )

    current_order.order_items.each do |item|
      charge = Stripe::Charge.create(
      :customer    => customer.id,
      :amount      => Integer(item.product.price*100*item.quantity),
      :description => 'Rails Stripe customer',
      :currency    => 'usd'
    )
  end
  
  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to new_charge_path
  end
end

app/controllers/homepage_controller.rb
class HomepageController < ApplicationController

  def index
  end
end

app/controllers/order_items_controller.rb
class OrderItemsController < ApplicationController

    def create
      @order = current_order
      @item = @order.order_items.new(item_params)
      @order.save
      session[:order_id] = @order.id
      redirect_to products_path
    end

    def destroy
      @order = current_order
      @item = @order.order_items.find(params[:id])
      @item.destroy
      @order.save
      redirect_to cart_path
    end

    private

    def item_params
      params.require(:order_item).permit(:quantity, :product_id)
    end
  end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy]

  # GET /orders
  # GET /orders.json
  def index
    @orders = Order.all
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
  end

  # GET /orders/new
  def new
    @order = Order.new
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(order_params)

    respond_to do |format|
      if @order.save
        format.html { redirect_to @order, notice: 'Order was successfully created.' }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url, notice: 'Order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.require(:order).permit(:status, :account_id, :total_price)
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
    @order_item = current_order.order_items.new
    @order_items = current_order.order_items
  end

  def user
    @user = User.find(current_user.id)
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
    @user = User.find(current_user.id)
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)
    @product.user_id = current_user.id
    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:price, :name, :description, :image, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/homepage_helper.rb
module HomepageHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/carts/show.erb
<% if @order_items.any? %>
    <% @order_items.each do |item| %>
      <p><%= item.product.name %> | <%= link_to "Delete", order_item_path(item), :data => {:confirm => "You sure?", :method => "delete"} %></p>
      <p> Unit Price: <%= number_to_currency item.product.price %> | Quantity: <%= item.quantity %> | Total Price: <%= number_to_currency (item.product.price * item.quantity) %></p>
    <% end %>
    <p>Your Total: <%= number_to_currency current_order.total_price %></p>
  <% else %>
    <p>Your shopping cart is empty.</p>
  <% end %>

app/views/charges/create.html.erb
<h2>Thanks, you paid <strong>$5.00</strong>!</h2>

app/views/charges/new.html.erb
<%= form_tag charges_path do %>
  <article>
    <% if flash[:error].present? %>
      <div id="error_explanation">
        <p><%= flash[:error] %></p>
      </div>
    <% end %>
    <label class="amount">
      <span>Amount: 500</span>
    </label>
  </article>

  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-description="A month's subscription"
          data-amount='<%= number_to_currency (item.product.price * item.quantity) %>'
          data-locale="auto"></script>
<% end %>

app/views/homepage/index.html.erb
<!DOCTYPE HTML>
<html>
<head>
<title>Watches an E-Commerce online Shopping Category Flat Bootstrap Responsive Website Template| Home :: w3layouts</title>


<link href="css/bootstrap.css" rel='stylesheet' type='text/css' />
<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
<!-- Custom Theme files -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

<!-- jQuery library -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>

<!-- Latest compiled JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">

	<link href='http://fonts.googleapis.com/css?family=PT+Sans:400,700' rel='stylesheet' type='text/css'>

	<link rel="stylesheet" href="css/reset.css"> <!-- CSS reset -->
	<link rel="stylesheet" href="css/style.css"> <!-- Gem style -->
	<script src="js/modernizr.js"></script> <!-- Modernizr -->
<!-- start menu -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

	<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
<script src="https://github.com/kswedberg/jquery-smooth-scroll/blob/master/jquery.smooth-scroll.min.js"></script>
<script>
$('.smooth').on('click', function() {
    $.smoothScroll({
        scrollElement: $('body'),
        scrollTarget: '#' + this.id
    });

    return false;
});
</script>

<!-- Navbar -->
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Elegant Touch</a>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav">
        <li class="active"><a href="#">Home</a></li>
        <li><%= link_to "Watches", products_path %></li>
        <li><a href="#">Page 3</a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <!-- <li><a href="#"><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>
        <li><a href="#"><span class="glyphicon glyphicon-log-in"></span> Login</a></li> -->
        <% if user_signed_in? %>
          <li>
          <%= link_to('Logout', destroy_user_session_path, :method => :delete) %><span class="glyphicon glyphicon-user"></span>
          </li>
        <% else %>
          <li>
          <%= link_to('Login', new_user_session_path)  %><span class="glyphicon glyphicon-log-in"></span>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

		<div id="page1" class ="smooth">
			<div id="myCarousel" class="carousel">

			<ol class = "carousel-indicators">
				<li data-target = "#myCarousel" data-slide-to = "0" class ="active"> </li>
				<li data-target = "#myCarousel" data-slide-to = "1"> </li>
				<li data-target = "#myCarousel" data-slide-to = "2"> </li>
			</ol>

			<div class = "carousel-inner">

				<div class = "item active">
					<img src = "http://en.lesrhabilleurs.com/wp-content/uploads/sites/2/2017/02/audemars-piguet-royal-oak-QP.jpg" alt = "" class = "img-responsive">
						<div class = "carousel-caption">
								<h3>Hello</h3>
						</div>
				</div>
				<div class = "item">
					<img src = "http://cdn1.hautetime.com/wp-content/uploads/2017/02/DSC01796.jpg" alt = "" class = "img-responsive">
					<div class = "carousel-caption">
							<h3>Hello</h3>
					</div>
				</div>
				<div class = "item">
					<img src = "https://manofmany.com/wp-content/uploads/2016/11/slide-1-image.jpg" alt = "" class = "img-responsive">
					<div class = "carousel-caption">
							<h3>Hello</h3>
					</div>
				</div>
			</div>

			<a class = "carousel-control left" href = "#myCarousel" data-slide = "prev">
				<span class = "icon-prev"></span>
			</a>
			<a class = "carousel-control right" href = "#myCarousel" data-slide = "next">
				<span class = "icon-next"></span>
			</a>
    </div><!-- /.carousel -->
	</div>

	<div class = "smooth">
		hello
	</div>

app/views/layouts/charges.html.erb
<!DOCTYPE html>
<html>
  <head></head>
  <body>
    <%= yield %>
  </body>
</html>

app/views/order_items/edit.html.erb
<h1>Editing Order Item</h1>

<%= render 'form', order_item: @order_item %>

<%= link_to 'Show', @order_item %> |
<%= link_to 'Back', order_items_path %>

app/views/order_items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Order Items</h1>

<table>
  <thead>
    <tr>
      <th>Quantity</th>
      <th>Product</th>
      <th>Order</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @order_items.each do |order_item| %>
      <tr>
        <td><%= order_item.quantity %></td>
        <td><%= order_item.product_id %></td>
        <td><%= order_item.order_id %></td>
        <td><%= link_to 'Show', order_item %></td>
        <td><%= link_to 'Edit', edit_order_item_path(order_item) %></td>
        <td><%= link_to 'Destroy', order_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Order Item', new_order_item_path %>

app/views/order_items/new.html.erb
<h1>New Order Item</h1>

<%= render 'form', order_item: @order_item %>

<%= link_to 'Back', order_items_path %>

app/views/order_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Quantity:</strong>
  <%= @order_item.quantity %>
</p>

<p>
  <strong>Product:</strong>
  <%= @order_item.product_id %>
</p>

<p>
  <strong>Order:</strong>
  <%= @order_item.order_id %>
</p>

<%= link_to 'Edit', edit_order_item_path(@order_item) %> |
<%= link_to 'Back', order_items_path %>

app/views/orders/edit.html.erb
<h1>Editing Order</h1>

<%= render 'form', order: @order %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

app/views/orders/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Orders</h1>

<table>
  <thead>
    <tr>
      <th>Status</th>
      <th>Account</th>
      <th>Total price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @orders.each do |order| %>
      <tr>
        <td><%= order.status %></td>
        <td><%= order.account_id %></td>
        <td><%= order.total_price %></td>
        <td><%= link_to 'Show', order %></td>
        <td><%= link_to 'Edit', edit_order_path(order) %></td>
        <td><%= link_to 'Destroy', order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Order', new_order_path %>

app/views/orders/new.html.erb
<h1>New Order</h1>

<%= render 'form', order: @order %>

<%= link_to 'Back', orders_path %>

app/views/orders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Status:</strong>
  <%= @order.status %>
</p>

<p>
  <strong>Account:</strong>
  <%= @order.account_id %>
</p>

<p>
  <strong>Total price:</strong>
  <%= @order.total_price %>
</p>

<%= link_to 'Edit', edit_order_path(@order) %> |
<%= link_to 'Back', orders_path %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<!DOCTYPE HTML>
<html>
<head>
<title>Watches an E-Commerce online Shopping Category Flat Bootstrap Responsive Website Template| Home :: w3layouts</title>


<link href="css/bootstrap.css" rel='stylesheet' type='text/css' />
<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
<!-- Custom Theme files -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

<!-- jQuery library -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>

<!-- Latest compiled JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">

	<link href='http://fonts.googleapis.com/css?family=PT+Sans:400,700' rel='stylesheet' type='text/css'>

	<link rel="stylesheet" href="css/reset.css"> <!-- CSS reset -->
	<link rel="stylesheet" href="css/style.css"> <!-- Gem style -->
	<script src="js/modernizr.js"></script> <!-- Modernizr -->
<!-- start menu -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

	<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
<script src="https://github.com/kswedberg/jquery-smooth-scroll/blob/master/jquery.smooth-scroll.min.js"></script>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

<script>

$('.smooth').on('click', function() {
    $.smoothScroll({
        scrollElement: $('body'),
        scrollTarget: '#' + this.id
    });

    return false;
});
</script>

<!-- Navbar -->

<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Elegant Touch</a>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav">
        <li class="active"><a href="#">Home</a></li>
        <li><%= link_to "Watches", products_path %></li>
        <li><a href="#">Page 3</a></li>
      </ul>


      <ul class="nav navbar-nav navbar-right">
        <!-- <li><a href="#"><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>
        <li><a href="#"><span class="glyphicon glyphicon-log-in"></span> Login</a></li> -->
				<!-- Single button -->
	<div class="dropdown">
	        <a href="#" data-toggle="dropdown" class="dropdown-toggle">Dropdown <b class="caret"></b></a>
	        <ul class="dropdown-menu">

						<table>
							 <caption>Your Cart:</caption>
						 <tr>
						 <th>Item</th>
						 <th>Unit Price</th>
						 <th>Quantity</th>
						 <th>Total</th>
						 </tr>
						 <% if @order_items.any? %>
								<% @order_items.each do |item| %>
						 <tr>
							 <td>
								 <p><%= item.product.name %> | <%= link_to "Delete", order_item_path(item), :data => {:confirm => "You sure?", :method => "delete"} %>
							 </td>
							 <td>
								 <%= number_to_currency item.product.price %>
							 </td>
							 <td>
								 <%= item.quantity %>
							 </td>
							 <td>
								 <%= number_to_currency (item.product.price * item.quantity) %>
							 </td>
						 </tr>
						 <%end%>
						</table>
						 <p>Your Total: <%= number_to_currency current_order.total_price %></p>
						 <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
										 data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
										 data-description="A month's subscription"
										 data-amount=<%= current_order.total_price * 100%>
										 data-locale="auto"></script>
						 <% else %>
						 <p>Your shopping cart is empty.</p>
						 <% end %>

	        </ul>
	    </div>
		</div>
</div>







        <% if user_signed_in? %>
          <li>
          <%= link_to('Logout', destroy_user_session_path, :method => :delete) %><span class="glyphicon glyphicon-user"></span>
          </li>
        <% else %>
          <li>
          <%= link_to('Login', new_user_session_path)  %><span class="glyphicon glyphicon-log-in"></span>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

  <!-- Grid box -->
	<% @products.in_groups_of(5, false).each do |group| %>
	  <div class='row'>
	    <% group.each do |product| %>
	      <div class='col-md-2 item'>
					<%= link_to product_path(product) do %>
							<%= image_tag product.image.url(:thumb) %>
							<% end %>
	        <h3><%= product.name %></h3>
	        <div><%=number_to_currency product.price%></div>
					<div class="button-edit">
					<%= button_to "Edit", edit_product_path(product),
								:class => "btn1", :method => :get %>
						<%= button_to 'Delete', product,:class => "btn3", method: :delete, data: { confirm: 'Are you sure?' } %>
						<%= button_to "New Product", new_product_path,
									:class => "btn1", :method => :get %>
						   <p><%= product.name %> | <%= number_to_currency product.price %>
						   <%= form_for @order_item do |f| %>
						     <%= f.hidden_field :product_id, value: product.id %>
						     <%= f.number_field :quantity %>
						     <%= f.submit "Add to cart" %>
						 <% end %></div>
	      </div>
	    <% end %>
	  </div>
	<% end %>

	<!-- <div class="row">

									<% @products.each do |product| %>

	              <div class="row col-xs-6">
	                <%= link_to product_path(product) do %>
	                    <%= image_tag product.image.url(:thumb) %>
	                <% end %>
								</div>
						</div>
								 <div class="row  col-sx-12">
									<%= button_to "Edit", edit_product_path(product),
									      :class => "btn1", :method => :get %>
									<%= button_to 'Delete', product,:class => "btn3", method: :delete, data: { confirm: 'Are you sure?' } %>
								</div>
							 <div class="row col-sx-12">
										<%= link_to product_path(product) do %>
		                    <%= product.name %>
		                <% end %>

	                <%= product.price %> $
								</div>
								<div class="row  col-sx-12">
	                <%= product.description %>
								</div>
	          	</ul>
						<%end%>
					</div>
</div> -->




  <!-- Grid box end -->











<!-- <h1>Products</h1>

<table>
  <thead>
    <tr>
      <th>Price</th>
      <th>Name</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.price %> $</td>
        <td><%= product.name %></td>
        <td><%= image_tag product.image.url(:thumb) %></td>
        <td><%= product.description %></td>
        <td><%= link_to 'Show', product %></td>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br> -->

<!-- <%= link_to 'New Product', new_product_path %>

<% @products.each do |product| %>
   <p><%= product.name %> | <%= number_to_currency product.price %>
   <%= form_for @order_item do |f| %>
     <%= f.hidden_field :product_id, value: product.id %>
     <%= f.number_field :quantity %>
     <%= f.submit "Add to cart" %>
   <% end %>
 <% end %>


 <% if @order_items.any? %>
     <% @order_items.each do |item| %>
       <p><%= item.product.name %> | <%= link_to "Delete", order_item_path(item), :data => {:confirm => "You sure?", :method => "delete"} %></p>
       <p> Unit Price: <%= number_to_currency item.product.price %> | Quantity: <%= item.quantity %> | Total Price: <%= number_to_currency (item.product.price * item.quantity) %></p>
     <% end %>
     <p>Your Total: <%= number_to_currency current_order.total_price %></p>
     <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
             data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
             data-description="A month's subscription"
             data-amount=<%= current_order.total_price * 100%>
             data-locale="auto"></script>
   <% else %>
     <p>Your shopping cart is empty.</p>
   <% end %> -->

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<%= image_tag@product.image.url(:medium) %>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>

<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>